name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE
      - AGENTS.md
      - docs/**
      - .gitignore

jobs:
  deploy-on-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build \
          -t ghcr.io/loadept/live.cursor:latest \
          -t ghcr.io/loadept/live.cursor:${{ github.sha }} \
          .

          docker push ghcr.io/loadept/live.cursor:latest
          docker push ghcr.io/loadept/live.cursor:${{ github.sha }}
